appname = pija_music_mid
httpport = 8081
runmode = dev
autorender = false
copyrequestbody = true
EnableDocs = true
sqlconn = 
servicio_api_artist= http://localhost:8081/v1/Artista
servicios_api_v1= http://localhost:8081/v1/
servicios_api_admin= http://localhost:8081/v1/Administrador
