appname = pija_music_mid
httpport = 8081
runmode = dev
autorender = false
copyrequestbody = true
EnableDocs = true
sqlconn = 
<<<<<<< HEAD
servicios_pija_music= http://localhost:8081/v1/
servicios_pija_music= http://localhost:8081/v1/Administrador
=======
servicios_pija_music= http://localhost:8081/v1/Artista
>>>>>>> 1a2750708638ac5850f9929506ba57b1caefdc2d
