appname = pija_music_mid
httpport = 8081
runmode = dev
autorender = false
copyrequestbody = true
EnableDocs = true
sqlconn = 
<<<<<<< HEAD
<<<<<<< HEAD
servicios_pija_music= http://localhost:8081/v1/
servicios_pija_music= http://localhost:8081/v1/Administrador
=======
servicios_pija_music= http://localhost:8081/v1/Artista
>>>>>>> 1a2750708638ac5850f9929506ba57b1caefdc2d
=======
servicio_api_artist= http://localhost:8081/v1/Artista
servicios_api_v1= http://localhost:8081/v1/
servicios_api_admin= http://localhost:8081/v1/Administrador
>>>>>>> bb8a6c48c5813c17a8c2a79fd57c65293c8e2619
servicios_api_admin= http://localhost:8081/v1/Canciones
servicios_api_admin= http://localhost:8081/v1/Comida